In [4]:
%pip install pandas numpy matplotlib seaborn openpyxl

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [10]:
file_path = r"HealthConnect_Appointment_Data.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [11]:
df.head()

,appointment_id,patient_id,gender,age,age_group,appointment_type,booking_date,appointment_date,appointment_day,appointment_time,booking_lead_days,previous_appointments,previous_no_shows,reminder_sent,reminder_channel,distance_to_clinic_km,waiting_time_minutes,appointment_outcome
0,HC-00001,P-1613,Female,39,35-44,Follow-up,2/6/2025,2/18/2025,Tuesday,Afternoon,12,2,0,Yes,WhatsApp,19.30,29.00,No-Show
1,HC-00002,P-0813,Male,31,25-34,Specialist Consultation,2/25/2026,2/27/2026,Friday,Morning,2,6,0,Yes,SMS,14.30,42.00,Attended
2,HC-00003,P-1366,Female,50,45-54,General Consultation,11/16/2025,12/24/2025,Wednesday,Morning,38,5,1,Yes,SMS,11.40,11.00,No-Show
3,HC-00004,P-1031,Male,59,55-64,Follow-up,7/18/2025,8/28/2025,Thursday,Evening,41,3,1,Yes,SMS,7.40,35.00,Attended
4,HC-00005,P-1458,Female,34,25-34,Follow-up,7/9/2025,8/25/2025,Monday,Afternoon,47,3,1,Yes,Email,5.60,27.00,No-Show

In [12]:
rows, columns = df.shape

print(f"Number of records: {rows:,}")
print(f"Number of columns: {columns}")

Number of records: 5,000
Number of columns: 18

In [13]:
print("Dataset Shape")
print("-" * 30)
print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

Dataset Shape
------------------------------
Rows    : 5,000
Columns : 18

In [14]:
print("Columns in the HealthConnect dataset:")
print("-" * 45)

for i, column in enumerate(df.columns, start=1):
    print(f"{i:02d}. {column}")

Columns in the HealthConnect dataset:
---------------------------------------------
01. appointment_id
02. patient_id
03. gender
04. age
05. age_group
06. appointment_type
07. booking_date
08. appointment_date
09. appointment_day
10. appointment_time
11. booking_lead_days
12. previous_appointments
13. previous_no_shows
14. reminder_sent
15. reminder_channel
16. distance_to_clinic_km
17. waiting_time_minutes
18. appointment_outcome

In [15]:
print("Data Types")
print("-" * 50)

df.dtypes

Data Types
--------------------------------------------------

appointment_id               str
patient_id                   str
gender                       str
age                        int64
age_group                    str
appointment_type             str
booking_date                 str
appointment_date             str
appointment_day              str
appointment_time             str
booking_lead_days          int64
previous_appointments      int64
previous_no_shows          int64
reminder_sent                str
reminder_channel             str
distance_to_clinic_km    float64
waiting_time_minutes     float64
appointment_outcome          str
dtype: object

In [16]:
data_types = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Non-Null Count": df.notna().sum().values,
    "Missing Count": df.isna().sum().values
})

data_types

                   Column Data Type  Non-Null Count  Missing Count
0          appointment_id       str            5000              0
1              patient_id       str            5000              0
2                  gender       str            5000              0
3                     age     int64            5000              0
4               age_group       str            5000              0
5        appointment_type       str            5000              0
6            booking_date       str            5000              0
7        appointment_date       str            5000              0
8         appointment_day       str            5000              0
9        appointment_time       str            5000              0
10      booking_lead_days     int64            5000              0
11  previous_appointments     int64            5000              0
12      previous_no_shows     int64            5000              0
13          reminder_sent       str            5000              0
14       reminder_channel       str            3634           1366
15  distance_to_clinic_km   float64            4910             90
16   waiting_time_minutes   float64            4940             60
17    appointment_outcome       str            5000              0

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   appointment_id         5000 non-null   str
 1   patient_id             5000 non-null   str
 2   gender                 5000 non-null   str
 3   age                    5000 non-null   int64
 4   age_group              5000 non-null   str
 5   appointment_type       5000 non-null   str
 6   booking_date           5000 non-null   str
 7   appointment_date       5000 non-null   str
 8   appointment_day        5000 non-null   str
 9   appointment_time       5000 non-null   str
 10  booking_lead_days      5000 non-null   int64
 11  previous_appointments  5000 non-null   int64
 12  previous_no_shows      5000 non-null   int64
 13  reminder_sent          5000 non-null   str
 14  reminder_channel       3634 non-null   str
 15  distance_to_clinic_km  4910 non-null   float64
 16  waiting_time_minutes   4940 non-null   float64
 17  appointment_outcome    5000 non-null   str
dtypes: float64(2), int64(4), str(12)
memory usage: 468.8 KB

In [18]:
df.head(10)

,appointment_id,patient_id,gender,age,age_group,appointment_type,booking_date,appointment_date,appointment_day,appointment_time,booking_lead_days,previous_appointments,previous_no_shows,reminder_sent,reminder_channel,distance_to_clinic_km,waiting_time_minutes,appointment_outcome
0,HC-00001,P-1613,Female,39,35-44,Follow-up,2/6/2025,2/18/2025,Tuesday,Afternoon,12,2,0,Yes,WhatsApp,19.30,29.00,No-Show
1,HC-00002,P-0813,Male,31,25-34,Specialist Consultation,2/25/2026,2/27/2026,Friday,Morning,2,6,0,Yes,SMS,14.30,42.00,Attended
2,HC-00003,P-1366,Female,50,45-54,General Consultation,11/16/2025,12/24/2025,Wednesday,Morning,38,5,1,Yes,SMS,11.40,11.00,No-Show
3,HC-00004,P-1031,Male,59,55-64,Follow-up,7/18/2025,8/28/2025,Thursday,Evening,41,3,1,Yes,SMS,7.40,35.00,Attended
4,HC-00005,P-1458,Female,34,25-34,Follow-up,7/9/2025,8/25/2025,Monday,Afternoon,47,3,1,Yes,Email,5.60,27.00,No-Show
5,HC-00006,P-0523,Male,66,65+,Specialist Consultation,2/16/2026,4/14/2026,Tuesday,Morning,57,4,2,No,NaN,3.10,36.00,No-Show
6,HC-00007,P-0776,Male,58,55-64,Diagnostic Test,1/17/2025,2/16/2025,Sunday,Afternoon,30,4,1,Yes,WhatsApp,8.20,30.00,No-Show
7,HC-00008,P-0927,Female,28,25-34,Specialist Consultation,11/27/2025,1/16/2026,Friday,Afternoon,50,6,1,Yes,SMS,19.20,21.00,Attended
8,HC-00009,P-0388,Male,77,65+,Follow-up,3/9/2025,4/21/2025,Monday,Afternoon,43,3,0,Yes,SMS,10.10,27.00,No-Show
9,HC-00010,P-0371,Female,20,18-24,Follow-up,2/5/2025,2/21/2025,Friday,Afternoon,16,2,0,Yes,SMS,28.00,20.00,Attended

In [19]:
df.tail(10)

,appointment_id,patient_id,gender,age,age_group,appointment_type,booking_date,appointment_date,appointment_day,appointment_time,booking_lead_days,previous_appointments,previous_no_shows,reminder_sent,reminder_channel,distance_to_clinic_km,waiting_time_minutes,appointment_outcome
4990,HC-04991,P-1139,Male,60,55-64,General Consultation,12/2/2025,12/21/2025,Sunday,Afternoon,19,3,2,No,NaN,11.90,38.00,No-Show
4991,HC-04992,P-0091,Female,64,55-64,General Consultation,9/30/2025,10/13/2025,Monday,Afternoon,13,1,0,Yes,WhatsApp,1.80,10.00,No-Show
4992,HC-04993,P-0070,Male,76,65+,Follow-up,5/2/2026,6/26/2026,Friday,Afternoon,55,8,2,Yes,SMS,12.10,28.00,No-Show
4993,HC-04994,P-0944,Male,38,35-44,Specialist Consultation,10/19/2025,10/29/2025,Wednesday,Morning,10,5,3,Yes,Email,13.20,29.00,No-Show
4994,HC-04995,P-0540,Prefer not to say,63,55-64,Follow-up,10/20/2025,12/17/2025,Wednesday,Afternoon,58,2,2,Yes,WhatsApp,0.90,23.00,No-Show
4995,HC-04996,P-0007,Male,49,45-54,Diagnostic Test,3/29/2025,4/26/2025,Saturday,Morning,28,5,1,Yes,Email,4.40,35.00,No-Show
4996,HC-04997,P-1501,Female,52,45-54,Follow-up,12/14/2025,2/12/2026,Thursday,Evening,60,6,2,Yes,WhatsApp,12.60,24.00,Attended
4997,HC-04998,P-0315,Male,59,55-64,General Consultation,3/3/2026,3/24/2026,Tuesday,Afternoon,21,5,0,No,NaN,22.80,28.00,Attended
4998,HC-04999,P-1262,Male,47,45-54,General Consultation,12/3/2025,1/6/2026,Tuesday,Morning,34,4,1,No,NaN,12.50,16.00,Attended
4999,HC-05000,P-1793,Female,19,18-24,General Consultation,8/24/2025,9/30/2025,Tuesday,Morning,37,6,1,Yes,WhatsApp,1.10,13.00,No-Show

In [20]:
duplicate_count = df.duplicated().sum()

print(f"Duplicate records: {duplicate_count:,}")

Duplicate records: 0

In [21]:
duplicate_appointments = df["appointment_id"].duplicated().sum()

print(f"Duplicate appointment IDs: {duplicate_appointments:,}")

Duplicate appointment IDs: 0

In [22]:
print(f"Unique appointment IDs: {df['appointment_id'].nunique():,}")
print(f"Total records: {len(df):,}")

Unique appointment IDs: 5,000
Total records: 5,000

In [23]:
unique_values = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": [df[column].nunique(dropna=True) for column in df.columns]
})

unique_values

                   Column  Unique Values
0          appointment_id           5000
1              patient_id           1696
2                  gender              3
3                     age             63
4               age_group              6
5        appointment_type              4
6            booking_date            593
7        appointment_date            545
8         appointment_day              7
9        appointment_time              3
10      booking_lead_days             61
11  previous_appointments             12
12      previous_no_shows              6
13          reminder_sent              2
14       reminder_channel              3
15  distance_to_clinic_km            335
16   waiting_time_minutes             62
17    appointment_outcome              3

In [24]:
categorical_columns = [
    "gender",
    "age_group",
    "appointment_type",
    "appointment_day",
    "appointment_time",
    "reminder_sent",
    "reminder_channel",
    "appointment_outcome"
]

for column in categorical_columns:
    print(f"\n{'=' * 50}")
    print(column.upper())
    print("=" * 50)
    print(df[column].value_counts(dropna=False))

==================================================
GENDER
==================================================
gender
Female               2488
Male                 2404
Prefer not to say     108
Name: count, dtype: int64

==================================================
AGE_GROUP
==================================================
age_group
65+      1241
35-44     819
55-64     800
45-54     793
25-34     783
18-24     564
Name: count, dtype: int64

==================================================
APPOINTMENT_TYPE
==================================================
appointment_type
General Consultation       2086
Follow-up                  1421
Specialist Consultation     900
Diagnostic Test             593
Name: count, dtype: int64

==================================================
APPOINTMENT_DAY
==================================================
appointment_day
Wednesday    737
Sunday       737
Friday       728
Saturday     724
Monday       701
Tuesday      689
Thursday     684
Name: count, dtype: int64

==================================================
APPOINTMENT_TIME
==================================================
appointment_time
Morning      2227
Afternoon    2094
Evening       679
Name: count, dtype: int64

==================================================
REMINDER_SENT
==================================================
reminder_sent
Yes    3634
No     1366
Name: count, dtype: int64

==================================================
REMINDER_CHANNEL
==================================================
reminder_channel
SMS         2000
NaN         1366
WhatsApp    1101
Email        533
Name: count, dtype: int64

==================================================
APPOINTMENT_OUTCOME
==================================================
appointment_outcome
No-Show      2423
Attended     2314
Cancelled     263
Name: count, dtype: int64

In [25]:
df.describe()

,age,booking_lead_days,previous_appointments,previous_no_shows,distance_to_clinic_km,waiting_time_minutes
count,"5,000.00","5,000.00","5,000.00","5,000.00","4,910.00","4,940.00"
mean,48.79,29.64,3.01,0.54,10.11,24.19
std,18.14,17.40,1.74,0.75,6.59,10.86
min,18.00,0.00,0.00,0.00,0.50,2.00
25%,33.00,15.00,2.00,0.00,5.30,17.00
50%,49.00,30.00,3.00,0.00,8.70,24.00
75%,64.00,45.00,4.00,1.00,13.50,32.00
max,80.00,60.00,11.00,5.00,45.00,68.00

In [26]:
numeric_columns = [
    "age",
    "booking_lead_days",
    "previous_appointments",
    "previous_no_shows",
    "distance_to_clinic_km",
    "waiting_time_minutes"
]

df[numeric_columns].describe().T

                         count  mean   std   min   25%   50%   75%   max
age                   5,000.00 48.79 18.14 18.00 33.00 49.00 64.00 80.00
booking_lead_days     5,000.00 29.64 17.40  0.00 15.00 30.00 45.00 60.00
previous_appointments 5,000.00  3.01  1.74  0.00  2.00  3.00  4.00 11.00
previous_no_shows     5,000.00  0.54  0.75  0.00  0.00  0.00  1.00  5.00
distance_to_clinic_km 4,910.00 10.11  6.59  0.50  5.30  8.70 13.50 45.00
waiting_time_minutes  4,940.00 24.19 10.86  2.00 17.00 24.00 32.00 68.00

In [27]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isna().sum(),
    "Missing Percentage": (
        df.isna().sum() / len(df) * 100
    ).round(2)
})

missing_summary = missing_summary[
    missing_summary["Missing Values"] > 0
].sort_values(
    "Missing Values",
    ascending=False
)

missing_summary

                       Missing Values  Missing Percentage
reminder_channel                 1366               27.32
distance_to_clinic_km              90                1.80
waiting_time_minutes               60                1.20

In [28]:
pd.crosstab(
    df["reminder_sent"],
    df["reminder_channel"],
    dropna=False
)

reminder_channel  Email   SMS  WhatsApp   NaN
reminder_sent
No                    0     0         0  1366
Yes                 533  2000      1101     0

In [30]:
df["booking_date"] = pd.to_datetime(
    df["booking_date"],
    errors="coerce"
)

df["appointment_date"] = pd.to_datetime(
    df["appointment_date"],
    errors="coerce"
)

In [31]:
print(df["booking_date"].dtype)
print(df["appointment_date"].dtype)

datetime64[us]
datetime64[us]

In [32]:
print(
    "Booking Date Range:",
    df["booking_date"].min().date(),
    "to",
    df["booking_date"].max().date()
)

print(
    "Appointment Date Range:",
    df["appointment_date"].min().date(),
    "to",
    df["appointment_date"].max().date()
)

Booking Date Range: 2024-11-07 to 2026-06-27
Appointment Date Range: 2025-01-01 to 2026-06-30

In [34]:
invalid_booking_dates = (
    df["booking_date"] > df["appointment_date"]
).sum()

print(
    f"Bookings occurring after appointment date: "
    f"{invalid_booking_dates:,}"
)

Bookings occurring after appointment date: 0

In [35]:
previous_no_show_distribution = (
    df["previous_no_shows"]
    .value_counts()
    .sort_index()
)

previous_no_show_distribution

previous_no_shows
0    2921
1    1548
2     438
3      78
4      12
5       3
Name: count, dtype: int64