In [1]:
import pandas as pd

df = pd.read_csv(
    "Sample - Superstore.csv",
    encoding="latin1"
)

missing_values = df.isnull().sum()

print(missing_values)

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [2]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [3]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [4]:
print(df[["Order Date", "Ship Date"]].dtypes)

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [5]:
print(df["Quantity"].min())
print(df["Quantity"].max())

1
14

In [6]:
print(df["Discount"].min())
print(df["Discount"].max())

0.0
0.8

In [7]:
print(df["Sales"].min())
print(df["Sales"].max())

0.444
22638.48

In [8]:
print(df["Profit"].min())
print(df["Profit"].max())

-6599.978
8399.976

In [9]:
df.shape

(9994, 21)

In [10]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [11]:
df.dtypes

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code               int64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [12]:
unique_values = df.nunique().sort_values()

unique_values

Country             1
Category            3
Segment             3
Region              4
Ship Mode           4
Discount           12
Quantity           14
Sub-Category       17
State              49
City              531
Postal Code       631
Customer ID       793
Customer Name     793
Order Date       1237
Ship Date        1334
Product Name     1850
Product ID       1862
Order ID         5009
Sales            5825
Profit           7287
Row ID           9994
dtype: int64

In [13]:
categorical_columns = [
    "Ship Mode",
    "Segment",
    "Category",
    "Sub-Category",
    "Region"
]

for column in categorical_columns:
    print(f"\n{column}")
    print(df[column].unique())

Ship Mode
<StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

Segment
<StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

Category
<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

Sub-Category
<StringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

Region
<StringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

In [14]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Row ID,9994.0,4997.5,1.0,2499.25,4997.5,7495.75,9994.0,2885.163629
Order Date,9994,2016-04-30 00:07:12.259355,2014-01-03 00:00:00,2015-05-23 00:00:00,2016-06-26 00:00:00,2017-05-14 00:00:00,2017-12-30 00:00:00,NaN
Ship Date,9994,2016-05-03 23:06:58.571142,2014-01-07 00:00:00,2015-05-27 00:00:00,2016-06-29 00:00:00,2017-05-18 00:00:00,2018-01-05 00:00:00,NaN
Postal Code,9994.0,55190.379428,1040.0,23223.0,56430.5,90008.0,99301.0,32063.69335
Sales,9994.0,229.858001,0.444,17.28,54.49,209.94,22638.48,623.245101
Quantity,9994.0,3.789574,1.0,2.0,3.0,5.0,14.0,2.22511
Discount,9994.0,0.156203,0.0,0.0,0.2,0.2,0.8,0.206452
Profit,9994.0,28.656896,-6599.978,1.72875,8.6665,29.364,8399.976,234.260108

In [15]:
df.describe(include="object").T

<ipython-input-15-32118ad17a77>:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object").T

              count unique              top  freq
Order ID       9994   5009   CA-2017-100111    14
Ship Mode      9994      4   Standard Class  5968
Customer ID    9994    793         WB-21850    37
Customer Name  9994    793    William Brown    37
Segment        9994      3         Consumer  5191
Country        9994      1    United States  9994
City           9994    531    New York City   915
State          9994     49       California  2001
Region         9994      4             West  3203
Product ID     9994   1862  OFF-PA-10001970    19
Category       9994      3  Office Supplies  6026
Sub-Category   9994     17          Binders  1523
Product Name   9994   1850  Staple envelope    48